package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.KotlinScriptFileBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.kotlinFile
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        kotlinFile {
            name = "Lib"
            id = "Lib"
            path = "lib.main.kts"
        }
    }
    steps {
        update<KotlinScriptFileBuildStep>(0) {
            name = "Libib"
            clearConditions()
            compiler = "%teamcity.tool.kotlin.compiler.bundled%"
        }
    }
}
